
package com.xmlsoccer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "FootballDataSoap", targetNamespace = "http://xmlsoccer.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface FootballDataSoap {


    /**
     * @param startDateString
     * @param teamId
     * @param endDateString
     * @param apiKey
     * @return returns com.xmlsoccer.GetHistoricMatchesByTeamAndDateIntervalResponse.GetHistoricMatchesByTeamAndDateIntervalResult
     */
    @WebMethod(operationName = "GetHistoricMatchesByTeamAndDateInterval", action = "http://xmlsoccer.com/GetHistoricMatchesByTeamAndDateInterval")
    @WebResult(name = "GetHistoricMatchesByTeamAndDateIntervalResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetHistoricMatchesByTeamAndDateInterval", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetHistoricMatchesByTeamAndDateInterval")
    @ResponseWrapper(localName = "GetHistoricMatchesByTeamAndDateIntervalResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetHistoricMatchesByTeamAndDateIntervalResponse")
    public com.xmlsoccer.GetHistoricMatchesByTeamAndDateIntervalResponse.GetHistoricMatchesByTeamAndDateIntervalResult getHistoricMatchesByTeamAndDateInterval(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "teamId", targetNamespace = "http://xmlsoccer.com/")
            String teamId,
            @WebParam(name = "startDateString", targetNamespace = "http://xmlsoccer.com/")
            String startDateString,
            @WebParam(name = "endDateString", targetNamespace = "http://xmlsoccer.com/")
            String endDateString);

    /**
     * @param email
     * @param apiKey
     * @param newIp
     * @return returns com.xmlsoccer.UpdateDynamicIpResponse.UpdateDynamicIpResult
     */
    @WebMethod(operationName = "UpdateDynamicIp", action = "http://xmlsoccer.com/UpdateDynamicIp")
    @WebResult(name = "UpdateDynamicIpResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "UpdateDynamicIp", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.UpdateDynamicIp")
    @ResponseWrapper(localName = "UpdateDynamicIpResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.UpdateDynamicIpResponse")
    public com.xmlsoccer.UpdateDynamicIpResponse.UpdateDynamicIpResult updateDynamicIp(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "email", targetNamespace = "http://xmlsoccer.com/")
            String email,
            @WebParam(name = "newIp", targetNamespace = "http://xmlsoccer.com/")
            String newIp);

    /**
     * @param startDateString
     * @param teamId
     * @param endDateString
     * @param apiKey
     * @return returns com.xmlsoccer.GetFixturesByDateIntervalAndTeamResponse.GetFixturesByDateIntervalAndTeamResult
     */
    @WebMethod(operationName = "GetFixturesByDateIntervalAndTeam", action = "http://xmlsoccer.com/GetFixturesByDateIntervalAndTeam")
    @WebResult(name = "GetFixturesByDateIntervalAndTeamResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetFixturesByDateIntervalAndTeam", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetFixturesByDateIntervalAndTeam")
    @ResponseWrapper(localName = "GetFixturesByDateIntervalAndTeamResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetFixturesByDateIntervalAndTeamResponse")
    public com.xmlsoccer.GetFixturesByDateIntervalAndTeamResponse.GetFixturesByDateIntervalAndTeamResult getFixturesByDateIntervalAndTeam(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "startDateString", targetNamespace = "http://xmlsoccer.com/")
            String startDateString,
            @WebParam(name = "endDateString", targetNamespace = "http://xmlsoccer.com/")
            String endDateString,
            @WebParam(name = "teamId", targetNamespace = "http://xmlsoccer.com/")
            String teamId);

    /**
     * @param seasonDateString
     * @param league
     * @param apiKey
     * @return returns com.xmlsoccer.GetFixturesByLeagueAndSeasonResponse.GetFixturesByLeagueAndSeasonResult
     */
    @WebMethod(operationName = "GetFixturesByLeagueAndSeason", action = "http://xmlsoccer.com/GetFixturesByLeagueAndSeason")
    @WebResult(name = "GetFixturesByLeagueAndSeasonResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetFixturesByLeagueAndSeason", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetFixturesByLeagueAndSeason")
    @ResponseWrapper(localName = "GetFixturesByLeagueAndSeasonResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetFixturesByLeagueAndSeasonResponse")
    public com.xmlsoccer.GetFixturesByLeagueAndSeasonResponse.GetFixturesByLeagueAndSeasonResult getFixturesByLeagueAndSeason(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "seasonDateString", targetNamespace = "http://xmlsoccer.com/")
            String seasonDateString,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league);

    /**
     * @param id
     * @param apiKey
     * @return returns com.xmlsoccer.GetHistoricMatchesByIDResponse.GetHistoricMatchesByIDResult
     */
    @WebMethod(operationName = "GetHistoricMatchesByID", action = "http://xmlsoccer.com/GetHistoricMatchesByID")
    @WebResult(name = "GetHistoricMatchesByIDResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetHistoricMatchesByID", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetHistoricMatchesByID")
    @ResponseWrapper(localName = "GetHistoricMatchesByIDResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetHistoricMatchesByIDResponse")
    public com.xmlsoccer.GetHistoricMatchesByIDResponse.GetHistoricMatchesByIDResult getHistoricMatchesByID(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "Id", targetNamespace = "http://xmlsoccer.com/")
            int id);

    /**
     * @param id
     * @param apiKey
     * @return returns com.xmlsoccer.GetHistoricMatchesByFixtureMatchIDResponse.GetHistoricMatchesByFixtureMatchIDResult
     */
    @WebMethod(operationName = "GetHistoricMatchesByFixtureMatchID", action = "http://xmlsoccer.com/GetHistoricMatchesByFixtureMatchID")
    @WebResult(name = "GetHistoricMatchesByFixtureMatchIDResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetHistoricMatchesByFixtureMatchID", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetHistoricMatchesByFixtureMatchID")
    @ResponseWrapper(localName = "GetHistoricMatchesByFixtureMatchIDResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetHistoricMatchesByFixtureMatchIDResponse")
    public com.xmlsoccer.GetHistoricMatchesByFixtureMatchIDResponse.GetHistoricMatchesByFixtureMatchIDResult getHistoricMatchesByFixtureMatchID(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "Id", targetNamespace = "http://xmlsoccer.com/")
            int id);

    /**
     * @param startDateString
     * @param league
     * @param endDateString
     * @param apiKey
     * @return returns com.xmlsoccer.GetHistoricMatchesByLeagueAndDateIntervalResponse.GetHistoricMatchesByLeagueAndDateIntervalResult
     */
    @WebMethod(operationName = "GetHistoricMatchesByLeagueAndDateInterval", action = "http://xmlsoccer.com/GetHistoricMatchesByLeagueAndDateInterval")
    @WebResult(name = "GetHistoricMatchesByLeagueAndDateIntervalResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetHistoricMatchesByLeagueAndDateInterval", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetHistoricMatchesByLeagueAndDateInterval")
    @ResponseWrapper(localName = "GetHistoricMatchesByLeagueAndDateIntervalResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetHistoricMatchesByLeagueAndDateIntervalResponse")
    public com.xmlsoccer.GetHistoricMatchesByLeagueAndDateIntervalResponse.GetHistoricMatchesByLeagueAndDateIntervalResult getHistoricMatchesByLeagueAndDateInterval(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league,
            @WebParam(name = "startDateString", targetNamespace = "http://xmlsoccer.com/")
            String startDateString,
            @WebParam(name = "endDateString", targetNamespace = "http://xmlsoccer.com/")
            String endDateString);

    /**
     * @param seasonDateString
     * @param league
     * @param apiKey
     * @return returns com.xmlsoccer.GetHistoricMatchesByLeagueAndSeasonResponse.GetHistoricMatchesByLeagueAndSeasonResult
     */
    @WebMethod(operationName = "GetHistoricMatchesByLeagueAndSeason", action = "http://xmlsoccer.com/GetHistoricMatchesByLeagueAndSeason")
    @WebResult(name = "GetHistoricMatchesByLeagueAndSeasonResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetHistoricMatchesByLeagueAndSeason", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetHistoricMatchesByLeagueAndSeason")
    @ResponseWrapper(localName = "GetHistoricMatchesByLeagueAndSeasonResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetHistoricMatchesByLeagueAndSeasonResponse")
    public com.xmlsoccer.GetHistoricMatchesByLeagueAndSeasonResponse.GetHistoricMatchesByLeagueAndSeasonResult getHistoricMatchesByLeagueAndSeason(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league,
            @WebParam(name = "seasonDateString", targetNamespace = "http://xmlsoccer.com/")
            String seasonDateString);

    /**
     * @param team2Id
     * @param startDateString
     * @param team1Id
     * @param endDateString
     * @param apiKey
     * @return returns com.xmlsoccer.GetHistoricMatchesByTeamsAndDateIntervalResponse.GetHistoricMatchesByTeamsAndDateIntervalResult
     */
    @WebMethod(operationName = "GetHistoricMatchesByTeamsAndDateInterval", action = "http://xmlsoccer.com/GetHistoricMatchesByTeamsAndDateInterval")
    @WebResult(name = "GetHistoricMatchesByTeamsAndDateIntervalResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetHistoricMatchesByTeamsAndDateInterval", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetHistoricMatchesByTeamsAndDateInterval")
    @ResponseWrapper(localName = "GetHistoricMatchesByTeamsAndDateIntervalResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetHistoricMatchesByTeamsAndDateIntervalResponse")
    public com.xmlsoccer.GetHistoricMatchesByTeamsAndDateIntervalResponse.GetHistoricMatchesByTeamsAndDateIntervalResult getHistoricMatchesByTeamsAndDateInterval(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "team1Id", targetNamespace = "http://xmlsoccer.com/")
            String team1Id,
            @WebParam(name = "team2Id", targetNamespace = "http://xmlsoccer.com/")
            String team2Id,
            @WebParam(name = "startDateString", targetNamespace = "http://xmlsoccer.com/")
            String startDateString,
            @WebParam(name = "endDateString", targetNamespace = "http://xmlsoccer.com/")
            String endDateString);

    /**
     * @param startDateString
     * @param endDateString
     * @param apiKey
     * @return returns com.xmlsoccer.GetFixturesByDateIntervalResponse.GetFixturesByDateIntervalResult
     */
    @WebMethod(operationName = "GetFixturesByDateInterval", action = "http://xmlsoccer.com/GetFixturesByDateInterval")
    @WebResult(name = "GetFixturesByDateIntervalResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetFixturesByDateInterval", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetFixturesByDateInterval")
    @ResponseWrapper(localName = "GetFixturesByDateIntervalResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetFixturesByDateIntervalResponse")
    public com.xmlsoccer.GetFixturesByDateIntervalResponse.GetFixturesByDateIntervalResult getFixturesByDateInterval(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "startDateString", targetNamespace = "http://xmlsoccer.com/")
            String startDateString,
            @WebParam(name = "endDateString", targetNamespace = "http://xmlsoccer.com/")
            String endDateString);

    /**
     * @param startDateString
     * @param league
     * @param endDateString
     * @param apiKey
     * @return returns com.xmlsoccer.GetFixturesByDateIntervalAndLeagueResponse.GetFixturesByDateIntervalAndLeagueResult
     */
    @WebMethod(operationName = "GetFixturesByDateIntervalAndLeague", action = "http://xmlsoccer.com/GetFixturesByDateIntervalAndLeague")
    @WebResult(name = "GetFixturesByDateIntervalAndLeagueResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetFixturesByDateIntervalAndLeague", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetFixturesByDateIntervalAndLeague")
    @ResponseWrapper(localName = "GetFixturesByDateIntervalAndLeagueResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetFixturesByDateIntervalAndLeagueResponse")
    public com.xmlsoccer.GetFixturesByDateIntervalAndLeagueResponse.GetFixturesByDateIntervalAndLeagueResult getFixturesByDateIntervalAndLeague(
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league,
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "startDateString", targetNamespace = "http://xmlsoccer.com/")
            String startDateString,
            @WebParam(name = "endDateString", targetNamespace = "http://xmlsoccer.com/")
            String endDateString);

    /**
     * @param apiKey
     * @return returns com.xmlsoccer.GetAllTeamsResponse.GetAllTeamsResult
     */
    @WebMethod(operationName = "GetAllTeams", action = "http://xmlsoccer.com/GetAllTeams")
    @WebResult(name = "GetAllTeamsResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetAllTeams", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetAllTeams")
    @ResponseWrapper(localName = "GetAllTeamsResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetAllTeamsResponse")
    public com.xmlsoccer.GetAllTeamsResponse.GetAllTeamsResult getAllTeams(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey);

    /**
     * @param apiKey
     * @return returns com.xmlsoccer.GetAllLeaguesResponse.GetAllLeaguesResult
     */
    @WebMethod(operationName = "GetAllLeagues", action = "http://xmlsoccer.com/GetAllLeagues")
    @WebResult(name = "GetAllLeaguesResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetAllLeagues", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetAllLeagues")
    @ResponseWrapper(localName = "GetAllLeaguesResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetAllLeaguesResponse")
    public com.xmlsoccer.GetAllLeaguesResponse.GetAllLeaguesResult getAllLeagues(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey);

    /**
     * @param seasonDateString
     * @param league
     * @param apiKey
     * @return returns com.xmlsoccer.GetLeagueStandingsBySeasonResponse.GetLeagueStandingsBySeasonResult
     */
    @WebMethod(operationName = "GetLeagueStandingsBySeason", action = "http://xmlsoccer.com/GetLeagueStandingsBySeason")
    @WebResult(name = "GetLeagueStandingsBySeasonResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetLeagueStandingsBySeason", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetLeagueStandingsBySeason")
    @ResponseWrapper(localName = "GetLeagueStandingsBySeasonResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetLeagueStandingsBySeasonResponse")
    public com.xmlsoccer.GetLeagueStandingsBySeasonResponse.GetLeagueStandingsBySeasonResult getLeagueStandingsBySeason(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league,
            @WebParam(name = "seasonDateString", targetNamespace = "http://xmlsoccer.com/")
            String seasonDateString);

    /**
     * @param seasonDateString
     * @param league
     * @param apiKey
     * @return returns com.xmlsoccer.GetAllTeamsByLeagueAndSeasonResponse.GetAllTeamsByLeagueAndSeasonResult
     */
    @WebMethod(operationName = "GetAllTeamsByLeagueAndSeason", action = "http://xmlsoccer.com/GetAllTeamsByLeagueAndSeason")
    @WebResult(name = "GetAllTeamsByLeagueAndSeasonResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetAllTeamsByLeagueAndSeason", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetAllTeamsByLeagueAndSeason")
    @ResponseWrapper(localName = "GetAllTeamsByLeagueAndSeasonResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetAllTeamsByLeagueAndSeasonResponse")
    public com.xmlsoccer.GetAllTeamsByLeagueAndSeasonResponse.GetAllTeamsByLeagueAndSeasonResult getAllTeamsByLeagueAndSeason(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league,
            @WebParam(name = "seasonDateString", targetNamespace = "http://xmlsoccer.com/")
            String seasonDateString);

    /**
     * @param league
     * @param apiKey
     * @return returns com.xmlsoccer.GetEarliestMatchDatePerLeagueResponse.GetEarliestMatchDatePerLeagueResult
     */
    @WebMethod(operationName = "GetEarliestMatchDatePerLeague", action = "http://xmlsoccer.com/GetEarliestMatchDatePerLeague")
    @WebResult(name = "GetEarliestMatchDatePerLeagueResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetEarliestMatchDatePerLeague", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetEarliestMatchDatePerLeague")
    @ResponseWrapper(localName = "GetEarliestMatchDatePerLeagueResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetEarliestMatchDatePerLeagueResponse")
    public com.xmlsoccer.GetEarliestMatchDatePerLeagueResponse.GetEarliestMatchDatePerLeagueResult getEarliestMatchDatePerLeague(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league);

    /**
     * @param apiKey
     * @return returns com.xmlsoccer.GetLiveScoreResponse.GetLiveScoreResult
     */
    @WebMethod(operationName = "GetLiveScore", action = "http://xmlsoccer.com/GetLiveScore")
    @WebResult(name = "GetLiveScoreResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetLiveScore", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetLiveScore")
    @ResponseWrapper(localName = "GetLiveScoreResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetLiveScoreResponse")
    public com.xmlsoccer.GetLiveScoreResponse.GetLiveScoreResult getLiveScore(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey);

    /**
     * @param league
     * @param apiKey
     * @return returns com.xmlsoccer.GetLiveScoreByLeagueResponse.GetLiveScoreByLeagueResult
     */
    @WebMethod(operationName = "GetLiveScoreByLeague", action = "http://xmlsoccer.com/GetLiveScoreByLeague")
    @WebResult(name = "GetLiveScoreByLeagueResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetLiveScoreByLeague", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetLiveScoreByLeague")
    @ResponseWrapper(localName = "GetLiveScoreByLeagueResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetLiveScoreByLeagueResponse")
    public com.xmlsoccer.GetLiveScoreByLeagueResponse.GetLiveScoreByLeagueResult getLiveScoreByLeague(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league);

    /**
     * @param teamName
     * @param apiKey
     * @return returns com.xmlsoccer.GetTeamResponse.GetTeamResult
     */
    @WebMethod(operationName = "GetTeam", action = "http://xmlsoccer.com/GetTeam")
    @WebResult(name = "GetTeamResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetTeam", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetTeam")
    @ResponseWrapper(localName = "GetTeamResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetTeamResponse")
    public GetTeamResponse.GetTeamResult getTeam(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "teamName", targetNamespace = "http://xmlsoccer.com/")
            String teamName);

    /**
     * @param fixtureMatchId
     * @param apiKey
     * @return returns com.xmlsoccer.GetOddsByFixtureMatchIdResponse.GetOddsByFixtureMatchIdResult
     */
    @WebMethod(operationName = "GetOddsByFixtureMatchId", action = "http://xmlsoccer.com/GetOddsByFixtureMatchId")
    @WebResult(name = "GetOddsByFixtureMatchIdResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetOddsByFixtureMatchId", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetOddsByFixtureMatchId")
    @ResponseWrapper(localName = "GetOddsByFixtureMatchIdResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.GetOddsByFixtureMatchIdResponse")
    public com.xmlsoccer.GetOddsByFixtureMatchIdResponse.GetOddsByFixtureMatchIdResult getOddsByFixtureMatchId(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "fixtureMatch_Id", targetNamespace = "http://xmlsoccer.com/")
            String fixtureMatchId);

    /**
     * @param apiKey
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "CheckApiKey", action = "http://xmlsoccer.com/CheckApiKey")
    @WebResult(name = "CheckApiKeyResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "CheckApiKey", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.CheckApiKey")
    @ResponseWrapper(localName = "CheckApiKeyResponse", targetNamespace = "http://xmlsoccer.com/", className = "com.xmlsoccer.CheckApiKeyResponse")
    public String checkApiKey(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey);

}
